### PR TITLE
Create CS50 Submit Access

### PR DESCRIPTION
**Pull request by liju-jacob**
Could you kindly grant access for CS50 submit as my workspace under liju-jacob cannot check and submit the lab projects. Thanks !

### CODE REVIEW

**Comment by ChakChakkk** [comment]
Sorry how do I do this?

**Comment by agrawal464** [comment]
how i can do this tell me

**Comment by Yvancg** [comment]
I seem to have 2 codespaces names under the same number. Is there a way to sync these 2 names so that they have the same content?

**Comment by vmyricks** [comment]
I am having trouble finding my directory even though ive created one. and not sure if i am in the correct code space to submit work.

**Comment by Dexacus** [comment]
I have 3 code spaces and I cant even figure out how to submit it or which one to do so. I am just going to keep taking the class. They aren't getting my money unless I get some help on how to submit.

**Pull request closed without merging**
